auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Life-note's Blog”
title: Life-note's blog
description: Everything about Life-note.
url: http://life-note.github.io
feed: /atom.xml
author_info: <a href="http://life-note.github.io/">Life-note</a>
